# Generated by Django 4.1.1 on 2024-05-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.URLField()),
                ('short_url', models.CharField(max_length=10, unique=True)),
                ('hits', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
